language: go

go:
  - 1.x

install: true

script:
  - set -e
  - fmt=$(gofmt -l .)
  - test -z $fmt || (echo "please run gofmt" ; echo $fmt ; exit 1)
  - go generate ...
  - git diff --quiet  || (echo 'generated go files are not up to date, check go generate, go.sum and go.mod' ; git diff ; exit 1)
  - go test -race -vet=all ./...