name: Tests

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  run-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ '1.*' ]
    name: Run tests
    steps:
      - uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
      - name: Get dependencies
        run: go get -v -t -d ./...
      - name: Test
        run: go test -race ./...
  static-checks:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ '1.*' ]
    name: Static checks
    steps:
      - uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
      - name: Get dependencies
        run: go get -v -t -d ./...
      - name: Go Vet
        run: go vet ./...
      - name: Go Fmt
        run: |
          fmt=$(gofmt -l .)
          test -z $fmt || (echo "please run gofmt" ; echo $fmt ; exit 1)
      - name: Go Lint
        run: go run golang.org/x/lint/golint -set_exit_status $(go list ./...)
      - name: Go Cyclo
        run: go run github.com/fzipp/gocyclo/cmd/gocyclo -top 30 -ignore graphql .
      - name: Spelling
        run: |
          find . -type f -name '*.go' | xargs go run github.com/client9/misspell/cmd/misspell -error
          find . -type f -name '*.md' | xargs go run github.com/client9/misspell/cmd/misspell -error
      - name: In effective assignments
        run: go run github.com/gordonklaus/ineffassign .